### PR TITLE
updates?

### PR DESCRIPTION
**Pull request by steven-lay**
Majority of these commits come directly from Linux kernel patches, but not all since most of them are unrelated drivers or whatever we don't have on our phones. Currently up to linux version 3.4.54, didn't really change Makefile to reflect this though.
Rest of the stuff are from other people like franco etc.

### CODE REVIEW

**Comment by Myself5** [comment]
Will test them tomorrow and merge if they work. Did you also merged the CM upstream here?

**Comment by steven-lay** [comment]
This repository is forked from your's on Jan 25th, so it has everything you
have before and including this date. Therefore it should be up-to-date with
the cm12.1 kernel too :P

**Comment by Myself5** [comment]
There's the problem, mine isnt updated :P Hence I was asking.
I'll check your commits tomorrow in combinition with CM upstream merged. Was quite busy in the last weeks, not being able to look into M5 A lot.

**Comment by steven-lay** [comment]
think i have kernel related crashes, please delay merge.

**Comment by steven-lay** [comment]
Well, now I have a large proportion of the commits up to linux 3.4.110, which is the last version of linux kernel 3.4, gonna test it now

**Comment by Myself5** [comment]
You should update the Makefile Version then ;)

**Comment by steven-lay** [comment]
Hahaha done, i've only tested it for a few hours but stable (so far).

**Comment by nos1609** [comment]
You've forgotten the scorpion and scorpion windy defconfigs, they're already adapted and tested by 80+ (36+16+19+5) installs

**Comment by Myself5** [comment]
@nos1609 You mean the defconfigs present here are already updated, or do I need to merge an additional PR from you to update them?

**Comment by steven-lay** [comment]
ehhh i can update those if you want

**Comment by nos1609** [comment]
@Myself5 I'm adding a scorpion_windy PR right now so everything is ready to go
@tomascus It would be nice, since it's the only custom kernel for these devices ported yet. I'm adding necessary PR for windy version right now, the scorpion defconfig was already merged several weeks ago. I saw there were 5 or 6 lines added on CM's gerrit concerning sk-hynix or something similar

**Pull request merged**
